### ISSUE TITLE
Support aliases

### ISSUE THREAD

**Issue by rchl** [jwortmann/quick-view#1]
Disclaimer: I have not tried this package yet and not sure if it would be useful in my workflow.

Having said that, I work with projects that refer to files using an alias. So for example a path like `~/assets/images/foo.png` refers to a directory `<repo>/app/assets/images/foo.png`. The alias can also be `~~`, `@` or `@@`.

It might be useful to support that. The user would define a map of aliases and according paths. Something like:

```
        "aliases": {
            "~": "app",
        },
```

Ideally the paths relative to the project directory would be supported or there would be support for expanding variables.

**Comment by jwortmann** [comment]
Thanks for the suggestion! Good idea, I will try to implement it.

**Comment by jwortmann** [comment]
I have added a setting for this named "path_substitutions" in f5db09f. It allows to expand variables provided by ST like $folder or $project_path as well. It worked when I did a simple test but maybe it still needs a bit of tweaking.

I guess I can assume that the aliases usually only occur at the beginning of the path? For now I (only) excluded the filename from such substitutions, because I think filenames like `icon@2x.png` are commonly used and in that case characters should not be replaced.

I think I will wait a bit (maybe a few weeks) before doing another release of this package unless there is a urgent demand for it, because I have some more ideas for possible features that I'd like to explore first.

**Comment by jwortmann** [comment]
I have renamed the setting to "path_aliases" and adjusted the logic a bit, so that it will only substitute aliases which occur at the start of an image path. I hope this is how these aliases work in the used frameworks.

I have just pushed a new tag for this package, so that it will be updated via Package Control soon.
