### ISSUE TITLE
Improved Instructions

### ISSUE THREAD

**Issue by dwhenson** [jwortmann/quick-view#3]
This package is great and does just what I wanted, but I'd to make it work for svg too. Can you add some more details to the instructions: "an installed image converter program available in the PATH and must be activated in the package settings." to make it clearer and easier to use?

**Comment by jwortmann** [comment]
For SVG previews you need to have either [Inkscape](https://inkscape.org/) or [ImageMagick](https://imagemagick.org/index.php) installed. Since Sublime's popups don't support the SVG format natively, the program will be used in the background to convert a SVG into a supported format (PNG). Inkscape seems to be slightly faster and I think it can handle complex SVGs better, but ImageMagick supports other image formats too.

After the installation you also need to add the path to the program executable to your PATH environment variable, so that the operating system can find it when the executable name is called from the command line. For Windows 10, you can adjust that environment variable (it is called "Path" on Windows) for example via the settings app. It looks looks like this for example for my Inkscape installation (of course dependent on where you installed the program):

![path](https://user-images.githubusercontent.com/6579999/119361097-92028400-bcab-11eb-9f2e-333fc6b7d5e2.png)

Some installers will also ask you if they should automatically add the installation directory to the PATH. See https://superuser.com/questions/284342/what-are-path-and-other-environment-variables-and-how-can-i-set-or-use-them for an extensive explanation on the topic.

After that you should restart Sublime Text and then open the package settings via *Preferences > Package Settings > QuickView* from the menu or *Preferences: QuickView Settings* from the command palette and configure the "svg_converter" setting in the panel on the right side.

I have slightly reworded the sentence in the Readme now, but I'd be happy to hear a suggestion how to further improve it.

**Comment by jwortmann** [comment]
Have you gotten it to work for SVG files now?

I'd like to close this issue now, but feel free to leave a message if it doesn't work for you, or if you have a suggestion how I can improve the instructions.

**Comment by dwhenson** [comment]
Apologies. I am just coming back to this. I have installed ImageMagick, but I can't understand the PATH issue despite the link above. We can close this as the problem is with my understanding.

**Comment by jwortmann** [comment]
Which operating system do you use? Can you run `magick --version` in a terminal (e.g. PowerShell or cmd.exe on Windows) and see if the program can be found there and prints some output? This `PATH` environment variable is used by the operating system to find program even if they are not in the current working directory. But it depends on the OS how to configure it.
